#!/bin/sh

DEFAULT_ORIGIN=editors/emacs

INSTALLED_VERSION=$(pkg query -e '%o == "editors/emacs" || %o == "editors/emacs-devel"' %o)

if [ -z "${INSTALLED_VERSION}" ]; then
    echo No installed version found. Installing emacs
    echo
    if ! pkg install -y $DEFAULT_ORIGIN; then
	echo Failed to install emacs
	exit 1
    else
	exec $0
    fi
fi

exit 0

# Local Variables:
# major-mode: shell-script-mode
# End:
